import {
  Activity,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Camera,
  Code2,
  Database,
  File,
  Folder,
  FolderKanban,
  Globe2,
  Headphones,
  Heart,
  Layers3,
  Lightbulb,
  Megaphone,
  MessageCircle,
  Music,
  Palette,
  Rocket,
  Settings2,
  Shield,
  ShoppingBag,
  Sparkles,
  Star,
  Target,
  Users,
  Zap,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";
import type { ProjectIcon } from "@/types/projects";

export type ProjectIconOption = {
  name: string;
  value: ProjectIcon;
  icon: LucideIcon;
};

export const projectIconOptions: ProjectIconOption[] = [
  { name: "Folder", value: "folder", icon: Folder },
  { name: "Kanban", value: "kanban", icon: FolderKanban },
  { name: "Rocket", value: "rocket", icon: Rocket },
  { name: "Briefcase", value: "briefcase", icon: BriefcaseBusiness },
  { name: "Layers", value: "layers", icon: Layers3 },
  { name: "Sparkles", value: "sparkles", icon: Sparkles },
  { name: "Target", value: "target", icon: Target },
  { name: "Code", value: "code", icon: Code2 },
  { name: "Globe", value: "globe", icon: Globe2 },
  { name: "Chart", value: "chart", icon: BarChart3 },
  { name: "Calendar", value: "calendar", icon: CalendarDays },
  { name: "Users", value: "users", icon: Users },
  { name: "Shopping", value: "shopping", icon: ShoppingBag },
  { name: "Lightbulb", value: "lightbulb", icon: Lightbulb },
  { name: "Heart", value: "heart", icon: Heart },
  { name: "Activity", value: "activity", icon: Activity },
  { name: "Zap", value: "zap", icon: Zap },
  { name: "Settings", value: "settings", icon: Settings2 },
  { name: "Message", value: "message", icon: MessageCircle },
  { name: "Database", value: "database", icon: Database },
  { name: "Shield", value: "shield", icon: Shield },
  { name: "Star", value: "star", icon: Star },
  { name: "Camera", value: "camera", icon: Camera },
  { name: "Music", value: "music", icon: Music },
  { name: "Building", value: "building", icon: Building2 },
  { name: "Megaphone", value: "megaphone", icon: Megaphone },
  { name: "Palette", value: "palette", icon: Palette },
  { name: "File", value: "file", icon: File },
  { name: "Headphones", value: "headphones", icon: Headphones },
];

export const projectEmojiOptions = [
  "🚀",
  "🎯",
  "💡",
  "🔥",
  "⚡",
  "✨",
  "💻",
  "🌎",
  "📱",
  "🛒",
  "📊",
  "🎨",
  "🧠",
  "🏆",
  "❤️",
  "🛠️",
  "📅",
  "💼",
  "🎵",
  "🌱",
  "🔐",
  "🤝",
  "📚",
  "⭐",
];